- name: bug
  color: F00000
  description: Something isn't working
- name: feature
  color: 0E8A16
  description: New feature or request
- name: docs
  color: 0075ca
  description: Improvements or additions to documentation
- name: chore
  color: FBCA04
  description: Routine tasks and maintenance
- name: enhancement
  color: a2eeef
  description: Enhancements or optimizations
- name: question
  color: d876e3
  description: Further information requested
