name = "print2"
pages_build_output_dir = "."
compatibility_date = "2024-11-01"

[env.preview]
  name = "print2"

[env.production]
  name = "print2"

# >>> BEGIN MANAGED BLOCK: ci-guard:cf-pages-build
# (pages_build_output_dir moved to top-level)
# <<< END MANAGED BLOCK: ci-guard:cf-pages-build
