name: Example CI anchors

on:
  workflow_dispatch:

x-checkout: &checkout
  uses: actions/checkout@v4
  with:
    fetch-depth: 0

x-setup-node: &setup-node
  uses: actions/setup-node@v4
  with:
    node-version: 20
    cache: npm

x-cache-node-modules: &cache-node-modules
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *cache-node-modules
      - run: npm test
