ALTER TABLE gifts
  ADD COLUMN IF NOT EXISTS printing_email_sent BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS shipping_email_sent BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS upsell_email_sent BOOLEAN DEFAULT FALSE;
