CREATE TABLE IF NOT EXISTS sale_credits (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  credit_cents INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER sale_credits_set_updated
BEFORE UPDATE ON sale_credits
FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
