#!/usr/bin/env bash
if [[ "$1" == "ping" ]]; then
  exit 0
fi
if [[ "$1" == "ci" && -z "$SIGINT_DONE" ]]; then
  echo "npm ERR! canceled" >&2
  echo "npm ERR! signal SIGINT" >&2
  export SIGINT_DONE=1
  exit 130
fi
exec "$REAL_NPM" "$@"
