openapi: 3.0.0
info:
  title: print2 API
  version: 1.0.0
paths:
  /api-docs:
    get:
      responses:
        "200":
          description: OK
  /api/register:
    post:
      responses:
        "200":
          description: OK
  /api/dalle:
    post:
      responses:
        "200":
          description: OK
  /api/generate-model:
    post:
      responses:
        "200":
          description: OK
  /api/login:
    post:
      responses:
        "200":
          description: OK
  /api/request-password-reset:
    post:
      responses:
        "200":
          description: OK
  /api/reset-password:
    post:
      responses:
        "200":
          description: OK
  /api/me:
    get:
      responses:
        "200":
          description: OK
  /api/generate:
    post:
      responses:
        "200":
          description: OK
  /api/upload-model:
    post:
      responses:
        "200":
          description: OK
  /api/models:
    get:
      responses:
        "200":
          description: OK
  /api/status:
    get:
      responses:
        "200":
          description: OK
  /api/status/:jobId:
    get:
      responses:
        "200":
          description: OK
  /api/config/stripe:
    get:
      responses:
        "200":
          description: OK
  /api/print-slots:
    get:
      responses:
        "200":
          description: OK
  /api/stats:
    get:
      responses:
        "200":
          description: OK
  /api/usernames:
    get:
      responses:
        "200":
          description: OK
  /api/recent-purchases:
    get:
      responses:
        "200":
          description: OK
  /api/campaign:
    get:
      responses:
        "200":
          description: OK
  /api/health:
    get:
      responses:
        "200":
          description: OK
  /api/init-data:
    get:
      responses:
        "200":
          description: OK
  /api/payment-init:
    get:
      responses:
        "200":
          description: OK
  /api/subreddit/:name:
    get:
      responses:
        "200":
          description: OK
  /api/progress/:jobId:
    get:
      responses:
        "200":
          description: OK
  /api/my/models:
    get:
      responses:
        "200":
          description: OK
  /api/my/orders:
    get:
      responses:
        "200":
          description: OK
  /api/commissions:
    get:
      responses:
        "200":
          description: OK
  /api/profile:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/profile/avatar:
    post:
      responses:
        "200":
          description: OK
  /api/account:
    delete:
      responses:
        "200":
          description: OK
  /api/stripe/connect:
    post:
      responses:
        "200":
          description: OK
  /api/subscription:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/subscription/cancel:
    post:
      responses:
        "200":
          description: OK
  /api/subscription/portal:
    post:
      responses:
        "200":
          description: OK
  /api/subscription/credits:
    get:
      responses:
        "200":
          description: OK
  /api/subscription/summary:
    get:
      responses:
        "200":
          description: OK
  /api/dashboard:
    get:
      responses:
        "200":
          description: OK
  /api/referral-link:
    get:
      responses:
        "200":
          description: OK
  /api/orders/:id/referral-link:
    get:
      responses:
        "200":
          description: OK
  /api/orders/:id/referral-qr:
    get:
      responses:
        "200":
          description: OK
  /api/referral-click:
    post:
      responses:
        "200":
          description: OK
  /api/referral-signup:
    post:
      responses:
        "200":
          description: OK
  /api/referral-post:
    post:
      responses:
        "200":
          description: OK
  /api/social-shares:
    post:
      responses:
        "200":
          description: OK
  /api/admin/social-shares/:id/verify:
    post:
      responses:
        "200":
          description: OK
  /api/rewards:
    get:
      responses:
        "200":
          description: OK
  /api/rewards/options:
    get:
      responses:
        "200":
          description: OK
  /api/rewards/redeem:
    post:
      responses:
        "200":
          description: OK
  /api/credits:
    get:
      responses:
        "200":
          description: OK
  /api/credits/redeem:
    post:
      responses:
        "200":
          description: OK
  /api/leaderboard:
    get:
      responses:
        "200":
          description: OK
  /api/achievements:
    get:
      responses:
        "200":
          description: OK
  /api/gifts/:id/claim:
    post:
      responses:
        "200":
          description: OK
  /api/track/ad-click:
    post:
      responses:
        "200":
          description: OK
  /api/track/page:
    post:
      responses:
        "200":
          description: OK
  /api/track/cart:
    post:
      responses:
        "200":
          description: OK
  /api/track/checkout:
    post:
      responses:
        "200":
          description: OK
  /api/track/share:
    post:
      responses:
        "200":
          description: OK
  /api/metrics/conversion:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/profit:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/business-intel:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/marginal-cac:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/daily-profit:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/daily-capacity:
    get:
      responses:
        "200":
          description: OK
  /api/metrics/demand-forecast:
    get:
      responses:
        "200":
          description: OK
  /api/users/:username/models:
    get:
      responses:
        "200":
          description: OK
  /api/users/:username/profile:
    get:
      responses:
        "200":
          description: OK
  /api/models/:id/like:
    post:
      responses:
        "200":
          description: OK
  /api/models/:id/public:
    post:
      responses:
        "200":
          description: OK
  /api/models/:id/share:
    post:
      responses:
        "200":
          description: OK
  /api/models/:id:
    delete:
      responses:
        "200":
          description: OK
  /api/shared/:slug:
    get:
      responses:
        "200":
          description: OK
  /api/community:
    post:
      responses:
        "200":
          description: OK
  /api/community/recent:
    get:
      responses:
        "200":
          description: OK
  /api/community/popular:
    get:
      responses:
        "200":
          description: OK
  /api/community/mine:
    get:
      responses:
        "200":
          description: OK
  /api/community/:id:
    delete:
      responses:
        "200":
          description: OK
  /api/community/model/:id:
    get:
      responses:
        "200":
          description: OK
  /api/community/:id/comments:
    get:
      responses:
        "200":
          description: OK
  /api/community/:id/comment:
    post:
      responses:
        "200":
          description: OK
  /api/competitions/active:
    get:
      responses:
        "200":
          description: OK
  /api/competitions/past:
    get:
      responses:
        "200":
          description: OK
  /api/competitions/winners:
    get:
      responses:
        "200":
          description: OK
  /api/competitions/:id/entries:
    get:
      responses:
        "200":
          description: OK
  /api/competitions/:id/comments:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/competitions/:id/enter:
    post:
      responses:
        "200":
          description: OK
  /api/competitions/:id/discount:
    post:
      responses:
        "200":
          description: OK
  /api/competitions/:id/vote:
    post:
      responses:
        "200":
          description: OK
  /api/designer-submissions:
    post:
      responses:
        "200":
          description: OK
  /api/designer-submissions/approved:
    get:
      responses:
        "200":
          description: OK
  /api/admin/designer-submissions/:id/approve:
    post:
      responses:
        "200":
          description: OK
  /api/admin/competitions:
    post:
      responses:
        "200":
          description: OK
  /api/admin/competitions/:id:
    put:
      responses:
        "200":
          description: OK
    delete:
      responses:
        "200":
          description: OK
  /api/commissions/:id/mark-paid:
    post:
      responses:
        "200":
          description: OK
  /api/payouts:
    post:
      responses:
        "200":
          description: OK
  /api/shipping-estimate:
    post:
      responses:
        "200":
          description: OK
  /api/discount-code:
    post:
      responses:
        "200":
          description: OK
  /api/generate-discount:
    post:
      responses:
        "200":
          description: OK
  /api/flash-sale:
    get:
      responses:
        "200":
          description: OK
  /api/admin/flash-sale:
    post:
      responses:
        "200":
          description: OK
  /api/admin/flash-sale/:id:
    delete:
      responses:
        "200":
          description: OK
  /api/admin/spaces:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/admin/hubs:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/admin/hubs/:id/printers:
    post:
      responses:
        "200":
          description: OK
  /api/admin/hubs/:id:
    put:
      responses:
        "200":
          description: OK
  /api/admin/hubs/:id/shipments:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /api/admin/ads/generate:
    post:
      responses:
        "200":
          description: OK
  /api/admin/ads/pending:
    get:
      responses:
        "200":
          description: OK
  /api/admin/ads/:id/approve:
    post:
      responses:
        "200":
          description: OK
  /api/admin/ads/:id/reject:
    post:
      responses:
        "200":
          description: OK
  /api/admin/subscription-metrics:
    get:
      responses:
        "200":
          description: OK
  /api/admin/scaling-events:
    get:
      responses:
        "200":
          description: OK
  /api/admin/operations:
    get:
      responses:
        "200":
          description: OK
  /api/create-order:
    post:
      responses:
        "200":
          description: OK
  /api/gifts:
    post:
      responses:
        "200":
          description: OK
  /api/cart/items:
    post:
      responses:
        "200":
          description: OK
  /api/cart/items/:id:
    patch:
      responses:
        "200":
          description: OK
    delete:
      responses:
        "200":
          description: OK
  /api/cart:
    get:
      responses:
        "200":
          description: OK
    delete:
      responses:
        "200":
          description: OK
  /api/cart/checkout:
    post:
      responses:
        "200":
          description: OK
  /api/subscribe:
    post:
      responses:
        "200":
          description: OK
  /api/competitions/subscribe:
    post:
      responses:
        "200":
          description: OK
  /api/competitions/notify:
    post:
      responses:
        "200":
          description: OK
  /api/confirm-subscription:
    get:
      responses:
        "200":
          description: OK
  /api/unsubscribe:
    get:
      responses:
        "200":
          description: OK
  /api/webhook/sendgrid:
    post:
      responses:
        "200":
          description: OK
  /api/webhook/stripe:
    post:
      responses:
        "200":
          description: OK
  /api/webhook/printer-complete:
    post:
      responses:
        "200":
          description: OK
  /api/print-jobs/:id:
    get:
      responses:
        "200":
          description: OK
components: {}
tags: []
