name: Setup pnpm
runs:
  using: composite
  steps:
    - run: corepack enable
      shell: bash
    - run: corepack prepare pnpm@9.0.0 --activate
      shell: bash
    - run: echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
      shell: bash
    - run: echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
      shell: bash
