#!/usr/bin/env bash
flag=/tmp/tarball_warn_done
if [[ "$1" == "ci" && ! -f "$flag" ]]; then
  echo "npm WARN tarball tarball data for foo@https://registry.npmjs.org/foo/-/foo-1.0.0.tgz (sha512-deadbeef) seems to be corrupted. Trying again." >&2
  touch "$flag"
  exit 1
fi
exec "$REAL_NPM" "$@"
