name: Setup

on:
  workflow_call:
    inputs:
      run:
        description: Command to execute after dependencies install
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - run: corepack enable
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - run: ${{ inputs.run }}
