name: Auto Rebase and Merge Queue

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase
        id: rebase
        uses: peter-evans/rebase@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment and label on failure
        if: steps.rebase.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Rebase failed due to conflicts. Please resolve and push again.'
            })
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['rebase-needed']
            })
  merge-queue:
    needs: rebase
    if: needs.rebase.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Queue for merge
        uses: peter-evans/merge-queue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          delete-branch: true
