name: binary scan

on:
  pull_request:
    paths-ignore:
      - allowed-binaries.txt

permissions:
  contents: read

jobs:
  scan:
    runs-on:
      - [self-hosted, linux, aws]
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan for new binary files
        run: scripts/guard/binary-scan.sh origin/${{ github.event.pull_request.base.ref }}
