name: Cache primer

env:
  HUSKY: 0

on:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  root-cache:
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
    timeout-minutes: 15

  backend-cache:
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci --prefix backend
    timeout-minutes: 15

  frontend-cache:
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci --prefix frontend
    timeout-minutes: 15
