name: CI Routing

on:
  workflow_call:
    inputs:
      use-self-hosted:
        type: boolean
        required: true
    outputs:
      runs-on:
        description: Runner labels
        value: ${{ jobs.route.outputs.labels }}

jobs:
  route:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.labels.outputs.labels }}
    steps:
      - id: labels
        uses: ./.github/actions/ci/use-self-hosted-labels
        with:
          use-self-hosted: ${{ inputs.use-self-hosted }}
