name: ci-sparse

env:
  HUSKY: 0

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            apps/**
            packages/**
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm -w run build
