name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - run: SKIP_PW_DEPS=1 npm run setup
      - run: npm run coverage
      - name: Check coverage thresholds
        run: node scripts/check-coverage.js
      - name: Validate LCOV report
        run: |
          if grep -qE '^TN:|^SF:' backend/coverage/lcov.info; then
            echo '✅ lcov.info is valid'
          else
            echo '❌ lcov.info malformed or missing'
            exit 1
          fi
      - run: cat backend/coverage/lcov.info | npx coveralls
