name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - run: npm ci
      - run: npm ci --prefix backend
      - run: npm run coverage -- --reporter=text-lcov | npx coveralls
