name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
      - run: SKIP_PW_DEPS=1 npm run setup
      - run: SKIP_PW_DEPS=1 npm run coverage
      - name: Coverage summary
        run: |
          node - <<'EOF'
          const s = require('./coverage/coverage-summary.json');
          console.log(`Statements: ${s.total.statements.pct}%`);
          console.log(`Branches: ${s.total.branches.pct}%`);
          console.log(`Functions: ${s.total.functions.pct}%`);
          console.log(`Lines: ${s.total.lines.pct}%`);
          EOF
      - name: Validate coverage-summary.json
        run: node -e "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json','utf-8')); console.log('✅ JSON ok')"
      - name: Check coverage thresholds
        run: node scripts/check-coverage.js
      - name: Validate LCOV report
        run: CHECK_LCOV=1 node scripts/run-jest.js backend/__tests__/lcovExists.test.js
      - name: Verify coverage summary
        run: node scripts/run-jest.js backend/__tests__/coverageSummaryExists.test.js
      - run: cat coverage/lcov.info | npx coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
