name: Debug Queue

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I ran on ${{ runner.os }} with job id ${{ github.run_id }}"
