name: Debug Queue

env:
  HUSKY: 0


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main, 0000production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I ran on ${{ runner.os }} with job id ${{ github.run_id }}"
