name: Debug Queue

env:
  HUSKY: 0


on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  debug:
    timeout-minutes: 15
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    steps:
      - run: echo "I ran on ${{ runner.os }} with job id ${{ github.run_id }}"
