name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: [self-hosted, linux, aws]
    permissions:
      contents: read
    steps:
      - uses: github/dependency-review-action@v4
        with:
          fail-on-severity: high
