name: docker-ci-layer-cache

env:
  HUSKY: 0

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'apps/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        run: docker buildx create --use
      - name: Build image with cache
        run: docker buildx build . --cache-from=type=gha --cache-to=type=gha,mode=max --tag tmp/test:ci --load

