name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SKIP_TESTS: 0
    steps:
      - uses: actions/checkout@v4
      - run: echo "Using npm"
      - name: Build Docker image
        run: docker build -t api:latest .
      - name: Scan image for vulnerabilities
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.49.1 image --severity CRITICAL,HIGH --exit-code 1 api:latest
