name: secret sentinel guard

on:
  pull_request:

jobs:
  secret-sentinel-guard:
    runs-on:
      - [self-hosted, linux, aws]
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Run guard
        run: bash scripts/ci-guard/secret-sentinel/check.sh
