name: Terraform validate

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/iac-validate.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform fmt
        working-directory: infra/terraform/ssm-runner
        run: terraform fmt -check
      - name: Terraform init
        working-directory: infra/terraform/ssm-runner
        run: terraform init
      - name: Terraform validate
        working-directory: infra/terraform/ssm-runner
        run: terraform validate
