name: Jest Early Warning

env:
  HUSKY: 0

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    uses: ./.github/workflows/_setup.yml
    env:
      CI: true
      JEST_SKIP_COVERAGE: true
    with:
      run: npm test --prefix backend -- --maxWorkers=50% --runInBand=false --silent --reporters=default
