name: Jest Early Warning

env:
  HUSKY: 0

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    timeout-minutes: 15
    uses: ./.github/workflows/backend-tests.yml
