name: LFS enforce / lfs-enforce
on: [pull_request]
jobs:
  lfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: git lfs ls-files
        run: git lfs ls-files --error
        continue-on-error: true
      - name: check LFS pointers
        run: npx -y ts-node --transpile-only scripts/ci/check-lfs.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
