name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/_setup.yml
    with:
      run: |
        npm run lint:root
        npm run lint --prefix frontend
        npm run lint --prefix backend
