name: Lint

on:
  push:
    branches: [main]
    paths:
      - frontend/**
      - backend/**
      - package.json
      - package-lock.json
      - pnpm-lock.yaml
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - frontend/**
      - backend/**
      - package.json
      - package-lock.json
      - pnpm-lock.yaml
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_setup.yml
    with:
      run: |
        npm run lint:root
        npm run lint --prefix frontend
        npm run lint --prefix backend
