name: Nightly CI

on:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/node.yml
