name: OpenAPI Lint

env:
  HUSKY: 0


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-audit --no-fund
      - run: npm run lint:md
      - run: npx @ibm/openapi-validator docs/openapi.yaml
