name: Weekly Operations Report

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # install pnpm (corepack) + project deps
      - run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm install --frozen-lockfile=false --color=false || \
            (echo 'ℹ️  Falling back to npm install' && npm install --no-audit --no-fund)

      - name: Check lock-file sync
        run: node scripts/ensure-lockfile.js
      - run: npm run send-ops-report
        working-directory: backend
