name: Package Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: azure/setup-helm@v4
      - name: Package chart
        run: |
          helm package deploy/helm/print3 --destination chart
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: chart/print3-*.tgz
