name: Playwright browsers cache

env:
  HUSKY: 0


on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-browsers:
    timeout-minutes: 15
    runs-on: [self-hosted, linux, aws]
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/ms-playwright-ffmpeg
          key: ${{ runner.os }}-playwright-${{ github.head_ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-${{ github.head_ref }}-
      - run: echo "Cache key: ${{ steps.cache-playwright.outputs.cache-primary-key }}"

      - name: Install Playwright browsers
        if: runner.os == 'Linux'
        run: npx playwright install --with-deps
