name: Sync pnpm lockfile

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

jobs:
  sync:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && (
        (github.event.action == 'labeled' && github.event.label.name == 'sync-lock') ||
        (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'sync-lock'))
      ))
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v5.0.0
      - run: corepack enable
      - uses: pnpm/action-setup@v4.1.0
        with:
          run_install: false
      - run: pnpm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync pnpm-lock.yaml"
          title: "chore: sync pnpm-lock.yaml"
          body: Update pnpm-lock.yaml
          branch: chore/sync-pnpm-lock
          add-paths: pnpm-lock.yaml
