name: pnpm guard

on:
  push:
    branches:
      - dev
      - 00000production
  pull_request:
    branches:
      - dev
      - 00000production
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: corepack enable && pnpm -v
      - run: pnpm install --no-frozen-lockfile
