name: Post-mortem reporter

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fail-test:
    runs-on:
      - [self-hosted, linux, aws, small]
      - ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Intentionally fail
        id: fail_step
        run: |
          echo "This step fails"
          exit 1
      - name: Upload logs
        if: failure()
        id: upload_logs
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ github.job }}-logs
          path: ${{ runner.temp }}/_github_workflow/*.log
      - name: Capture log url
        if: failure()
        id: logs
        run: echo "url=${{ steps.upload_logs.outputs.artifact-url }}" >> "$GITHUB_OUTPUT"
      - name: Comment on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "❌ ${{ github.job }} failed at ${{ steps.fail_step.id }}. Logs: ${{ steps.logs.outputs.url }}"
