name: pr-path-filters

on:
  pull_request:
    paths:
      - 'apps/site/**'
      - 'packages/ui/**'

jobs:
  lint-typecheck:
    runs-on:
      - [self-hosted, linux, aws, small]
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/ensure-pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
