name: Preflight

env:
  HUSKY: 0

on:
  push:
    branches: [main]
    paths:
      - backend/**
      - package.json
      - package-lock.json
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - backend/**
      - package.json
      - package-lock.json
      - .github/workflows/**
  merge_group:
  workflow_call:
    outputs:
      run_backend:
        description: Run backend jobs
        value: ${{ jobs.changed.outputs.backend }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    timeout-minutes: 15
    runs-on:
      - [self-hosted, linux, aws]
      - ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/**'
