name: root-ci

on:
  push:
  pull_request:

jobs:
  root-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: SKIP_PW_DEPS=1 npm run ci
