name: Secret Scan

env:
  HUSKY: 0

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    runs-on:
      - [self-hosted, linux, aws]
      - [self-hosted, linux, x64, ci-small]
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Run gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        with:
          args: '--log-opts "${{ github.event.pull_request.base.sha }}..${{ github.sha }}" --report-format sarif --report-path gitleaks-report.sarif --redact'
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: gitleaks-report
          path: gitleaks-report.sarif
