name: Sync Labels

env:
  HUSKY: 0

on:
  push:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    timeout-minutes: 15
    runs-on:
      - [self-hosted, linux, aws, small]
      - ubuntu-latest
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
