name: Typecheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    uses: ./.github/workflows/_setup.yml
    with:
      run: npx tsc --noEmit
