name: Refresh NPM cache

env:
  HUSKY: 0

on:
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-
      - run: npm ci
      - run: npm ci --prefix backend
      - run: npm ci --prefix frontend
