name: web-matrix

env:
  HUSKY: 0

on:
  pull_request:
    paths:
      - "apps/site/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - [self-hosted, linux, aws, small]
      - ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Heartbeat
        run: |
          while true; do date; sleep 120; done &
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 1
          sparse-checkout: |
            apps/site
            package.json
            pnpm-lock.yaml
          sparse-checkout-cone: true
      - uses: ./.github/actions/ensure-pnpm
        with:
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Build
        run: pnpm -w run build
