---
name: YAML Validate
on:
  pull_request:
  push:
    branches: [main, dev]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: actionlint
        uses: rhysd/actionlint@v1.7.7
      - name: Install yamllint
        run: sudo pip install yamllint
      - name: yamllint (workflows & actions)
        run: |
          yamllint -d '{extends: default, rules: {line-length: {max: 140}}}' \
            .github/workflows \
            .github/actions
